command:
  - "python"
  - "app.py"

env:
     - name: LAKEBASE_INSTANCE_NAME
       value: "assignment1-db"
     - name: LAKEBASE_PG_ROLE
       value: "ajinkya.ambike@gmail.com"
     - name: LAKEBASE_DATABASE
       value: "databricks_postgres"
