command:
  - "python"
  - "app.py"

env:
     - name: LAKEBASE_INSTANCE_NAME
       value: "<your-instance-name>"
     - name: LAKEBASE_PG_ROLE
       value: "<your-postgres-role>"
     #optional, defaults to "databricks_postgres"
     - name: LAKEBASE_DATABASE
       value: "supportdb"
